// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzf5bISKAW2TgbzXELZ8NhdiKKY2Jp5rY',
    appId: '1:657368956029:web:ec53304f09705117954514',
    messagingSenderId: '657368956029',
    projectId: 'flashcards-bb53c',
    authDomain: 'flashcards-bb53c.firebaseapp.com',
    storageBucket: 'flashcards-bb53c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfcWXCt70DPmUGdUa5YoVLMbHc38TgcZc',
    appId: '1:657368956029:android:ff8e1875de7be9fb954514',
    messagingSenderId: '657368956029',
    projectId: 'flashcards-bb53c',
    storageBucket: 'flashcards-bb53c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTbKSNQlZdyL1apGcn4obax7QFk28qbRQ',
    appId: '1:657368956029:ios:19ccf24753354c23954514',
    messagingSenderId: '657368956029',
    projectId: 'flashcards-bb53c',
    storageBucket: 'flashcards-bb53c.appspot.com',
    iosClientId: '657368956029-2huq8daqeeu1k9n9f2icnrn988u20p9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTbKSNQlZdyL1apGcn4obax7QFk28qbRQ',
    appId: '1:657368956029:ios:a42a75224a1c9788954514',
    messagingSenderId: '657368956029',
    projectId: 'flashcards-bb53c',
    storageBucket: 'flashcards-bb53c.appspot.com',
    iosClientId: '657368956029-qdrul9sjnlospgal94gn3rfb5pcgn4vd.apps.googleusercontent.com',
    iosBundleId: 'com.flashcrdsapp.flashcards',
  );
}
